[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
nat-detect.workspace = true
env_logger.workspace = true
log.workspace = true
dotenv.workspace = true
bytes.workspace = true
